apiVersion: v1
kind: Namespace
metadata:
  name: cinciti-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cinciti-admin
  name: cinciti-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinciti-admin
  template:
    metadata:
      labels:
        app: cinciti-admin
    spec:
      containers:
        - name: cinciti-admin
          ports:
            - containerPort: 80
          image: registry.digitalocean.com/pookid/cinciti-admin:1.0.1
          livenessProbe:
                 httpGet:
                     path: /index.html
                     port: 80
                 initialDelaySeconds: 15
                 timeoutSeconds: 2
                 periodSeconds: 5
                 failureThreshold: 1
          readinessProbe:
                 httpGet:
                     path: /index.html
                     port: 80
                 initialDelaySeconds: 15
                 periodSeconds: 5
                 failureThreshold: 1
      imagePullSecrets:
        - name: pookid
---
apiVersion: v1
kind: Service
metadata:
  name: cinciti-admin
  namespace: cinciti-admin
  labels:
    app: cinciti-admin
spec:
  type: ClusterIP
  selector:
    app: cinciti-admin
  ports:
    - port: 80
      name: http
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinciti-admin
  namespace: cinciti-admin
  annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app: cinciti-admin
spec:
  rules:
    - host: "admin.cinciti.com"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: cinciti-admin
                port:
                  number: 80
